# Generated by Django 5.1 on 2024-10-06 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='period',
            field=models.CharField(choices=[('Ежедневная', 'Ежедневная'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], default='Ежедневная', max_length=20, verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 6, 11, 7, 4, 688345, tzinfo=datetime.timezone.utc), null=True, verbose_name='Время старта'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='stop_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 13, 11, 7, 4, 688345, tzinfo=datetime.timezone.utc), null=True, verbose_name='Время окончания'),
        ),
    ]
