# Generated by Django 5.1 on 2024-10-06 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_emailsettings_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingmessage',
            name='client',
            field=models.ManyToManyField(to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 6, 14, 30, 54, 356789, tzinfo=datetime.timezone.utc), null=True, verbose_name='Время старта'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='stop_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 13, 14, 30, 54, 356789, tzinfo=datetime.timezone.utc), null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='maillog',
            name='try_status',
            field=models.CharField(choices=[('Успешно', 'Успешно'), ('Ошибка', 'Ошибка')], default='Успешно', verbose_name='Статус попытки'),
        ),
    ]
