# Generated by Django 5.1 on 2024-10-06 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_emailsettings_client_alter_emailsettings_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsettings',
            name='client',
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 6, 16, 26, 18, 951046, tzinfo=datetime.timezone.utc), null=True, verbose_name='Время старта'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='stop_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 13, 16, 26, 18, 951046, tzinfo=datetime.timezone.utc), null=True, verbose_name='Время окончания'),
        ),
    ]
