# Generated by Django 5.1 on 2024-10-15 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_emailsettings_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Блокировка клиента'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='is_on',
            field=models.BooleanField(default=True, verbose_name='Активация рассылки'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 15, 17, 11, 40, 265445, tzinfo=datetime.timezone.utc), null=True, verbose_name='Время старта'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='stop_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 22, 17, 11, 40, 265445, tzinfo=datetime.timezone.utc), null=True, verbose_name='Время окончания'),
        ),
    ]
