# Generated by Django 5.1 on 2024-09-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Запись в блоге', 'verbose_name_plural': 'Записи в блоге'},
        ),
    ]
