# Generated by Django 5.1 on 2024-09-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_blog_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
